import { Archivo } from "next/font/google"; // Replace with Archivo
import "./globals.css";
import Topbar from "./components/Topbar";
import Footer from "./components/Footer";
// Import Archivo fonts
const archivo = Archivo({
  variable: "--font-archivo-sans",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500"], // Specify the weights you want
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Viewport meta tag for mobile responsiveness */}
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, user-scalable=no"
        />
      </head>
      <body className={`${archivo.variable}  antialiased`}>
        <Topbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
